### ISSUE TITLE
[Bug] attempt to render \t (tab) cast-out the characters after the \t

### ISSUE THREAD

**Issue by positron-dev** [coderoyalty/hyper#14]
when I was trying to render this text: "Hello\tWorld", the "World" was not rendered, just the "Hello" part.

seems like is not supported

**Comment by coderoyalty** [comment]
This potential bug happens here:

https://github.com/coderoyalty/hyper/blob/c428c9a095ffda3f58db0ce567fca9792147f8f8/engine/src/renderer/renderer2d.cpp#L258-L262

the renderer does not handle tabs (\t), and it's assumed that we can access the glyph of that character (which doesn't exist). The potential fix will be to skip or replace it with &#127; or a question mark (when we can't find a glyph for the character).
