### ISSUE TITLE
File dialogs for all platform

### ISSUE THREAD

**Issue by positron-dev** [coderoyalty/hyper#23]
File dialogs are only available for windows.

https://github.com/coderoyalty/hyper/blob/cbd54aa6cf60c60936693e85a1baa607c6eb3ea3/engine/src/utils/file_dialog.cpp#L7-L69

It'll be cumbersome to write codes for all platforms... best to use a package that already abstracts this..

**Comment by coderoyalty** [comment]
https://github.com/native-toolkit/libtinyfiledialogs

**Comment by coderoyalty** [comment]
Hyper hasn't been tested on other platforms. But, the goal is for the engine not to be platform-specific. To achieve this, we use libraries/packages that are not platform-specific. Development is actively happening on Windows, and the application is not expected to run on other platforms successfully.
